// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQqI2uSY8eckTBgrY-NCwUGCeCMiN7U7U',
    appId: '1:1087120768198:web:30c89262d33613cd43abc7',
    messagingSenderId: '1087120768198',
    projectId: 'zahra-medsense',
    authDomain: 'zahra-medsense.firebaseapp.com',
    storageBucket: 'zahra-medsense.firebasestorage.app',
    measurementId: 'G-L6X2TGQJR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBDPje2evBAi1Ki3PcKl5tRuqyR9OSqiY',
    appId: '1:1087120768198:android:60f87706307fd12443abc7',
    messagingSenderId: '1087120768198',
    projectId: 'zahra-medsense',
    storageBucket: 'zahra-medsense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe-oHmJejwBTBRPlkVUV7xSc88cg1XpjE',
    appId: '1:1087120768198:ios:9881a5c63bb7e3fa43abc7',
    messagingSenderId: '1087120768198',
    projectId: 'zahra-medsense',
    storageBucket: 'zahra-medsense.firebasestorage.app',
    iosBundleId: 'com.example.zahraMedsense',
  );
}
